---

ilm_mongo::disable_hugepages: '/etc/init.d/disable-transparent-hugepages'
ilm_mongo::version: '3.0.4'
ilm_mongo::replset_members:
  - graylog-mongo01:27017
  - graylog-mongo02:27017
  - graylog-mongo03:27017

ilm_elastic::version: '2.3.5'
ilm_elastic::elastic_hosts:
  - graylog-elasticsearch01
  - graylog-elasticsearch02
  - graylog-elasticsearch03

# Tested version 2.0.0-5 - Available version 2.0.0-6, 2.0.1-1, 2.0.2-1 & 2.0.3-1
ilm_graylog::repo_version: '2.0'
ilm_graylog::version: '2.0.3-1'
ilm_graylog::elasticsearch_shards: '4'
ilm_graylog::elasticsearch_replicas: '1'
ilm_graylog::mongodb_uri: 'mongodb://graylog-mongo01,graylog-mongo02,graylog-mongo03/graylog2'
ilm_graylog::elasticsearch_hosts: 'graylog-elasticsearch01:9300, graylog-elasticsearch02:9300, graylog-elasticsearch03:9300'
